---
abstract: 'Data Validation for Hierarchical Data'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class-Domain
requires:
  Hash::Flatten: 0
  Validation::Class: 0
resources:
  bugtracker: https://github.com/alnewkirk/Validation-Class-Domain/issues
  homepage: https://github.com/alnewkirk/Validation-Class-Domain
  repository: git://github.com/alnewkirk/Validation-Class-Domain.git
version: 0.000003
